dist: bionic
language: python
python:
  - "3.8.0"

services:
  - docker

jobs:
  include:
    - stage: Build Images
      script:
      - docker info
      - make build
      - docker images
    - stage: Release Images
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - make release